(part "RC0402FR-07100RL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "YAGEO")
    (property "Manufacturer_Part_Number" "RC0402FR-07100RL")
    (property "Mouser_Part_Number" "603-RC0402FR-07100RL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/RC0402FR-07100RL?qs=V1yeUXFNrknwaJOOZ4yDtg%3D%3D")
    (property "Arrow_Part_Number" "RC0402FR-07100RL")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/rc0402fr-07100rl/yageo?region=nac")
    (property "Description" "ic")
    (property "Datasheet_Link" "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_10.pdf")
    (property "symbolName1" "RC0402FR-07100RL")
)
