(part "PAM8906M1018-13"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "BOOT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SW") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUTP") (portType INOUT))
        (port "8" (symbPinId 8) (portName "FB") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DIN") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VIN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "PAM8906M1018-13")
    (property "Mouser_Part_Number" "621-PAM8906M1018-13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/PAM8906M1018-13?qs=amGC7iS6iy89BpBhX%252BV0cg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Audio Amplifiers Audio Low Volt MSOP-10 T&R 2.5K")
    (property "Datasheet_Link" "https://www.diodes.com/assets/Datasheets/PAM8906.pdf")
    (property "symbolName1" "PAM8906M1018-13")
)
