(part "0402B104K160CT"
    (packageRef "CAPC1005X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "Walsin Technology Corporation")
    (property "Manufacturer_Part_Number" "0402B104K160CT")
    (property "Mouser_Part_Number" "791-0402B104K160CT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Walsin/0402B104K160CT?qs=fIkAfuXiAQJ1PS4dYXnTSQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 0.1 uF 10% 16V")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/0402B104K160CT.pdf")
    (property "symbolName1" "0402B104K160CT")
)
