(part "0402WGF1002TCE"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "UNI-ROYAL(Uniroyal Elec)")
    (property "Manufacturer_Part_Number" "0402WGF1002TCE")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Chip Resistor - Surface Mount 10KOhms +/-1% 1/16W 0402 RoHS")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/Uniroyal-Elec-0402WGF1002TCE_C25744.pdf")
    (property "symbolName1" "0402WGF1002TCE")
)
